FROM node:22-alpine AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG CHECKOUT_API_BASE_URL
ARG CHECKOUT_PROCESSING_CHANNEL_ID
ARG NEXT_PUBLIC_CHECKOUT_PUBLIC_KEY
ARG NEXT_PUBLIC_CHECKOUT_PROCESSING_CHANNEL_ID
ARG APP_URL
ARG WEBHOOK_PUBLIC_URL
ARG CHECKOUT_WEBHOOK_WORKFLOW_ID

ENV CHECKOUT_API_BASE_URL=$CHECKOUT_API_BASE_URL
ENV CHECKOUT_PROCESSING_CHANNEL_ID=$CHECKOUT_PROCESSING_CHANNEL_ID
ENV NEXT_PUBLIC_CHECKOUT_PUBLIC_KEY=$NEXT_PUBLIC_CHECKOUT_PUBLIC_KEY
ENV NEXT_PUBLIC_CHECKOUT_PROCESSING_CHANNEL_ID=$NEXT_PUBLIC_CHECKOUT_PROCESSING_CHANNEL_ID
ENV APP_URL=$APP_URL
ENV WEBHOOK_PUBLIC_URL=$WEBHOOK_PUBLIC_URL
ENV CHECKOUT_WEBHOOK_WORKFLOW_ID=$CHECKOUT_WEBHOOK_WORKFLOW_ID

RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
